name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  timezone: ^0.9.2
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/shoppylist_logo.png"
  adaptive_icon_background: "#434153"
  adaptive_icon_foreground: "assets/icon/shoppylist_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/languages/en.json
    - assets/languages/de.json
    - assets/languages/fr.json
    - assets/languages/it.json
    - assets/languages/es.json
