// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCafUqHsN9Yae7DqO-QOQ8TN5KRRCAES-0',
    appId: '1:779857018826:web:abf7d6d8ff3a51210f5933',
    messagingSenderId: '779857018826',
    projectId: 'shoppylist-519ba',
    authDomain: 'shoppylist-519ba.firebaseapp.com',
    storageBucket: 'shoppylist-519ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvBbjoWbAM-8AS0sBLBlESr_fqKOZm6c',
    appId: '1:779857018826:android:219dd4891e4ea0110f5933',
    messagingSenderId: '779857018826',
    projectId: 'shoppylist-519ba',
    storageBucket: 'shoppylist-519ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtbBG3yWpUp5VjPsb8VPBXCwfedHVZflw',
    appId: '1:779857018826:ios:570a658c3bd323a30f5933',
    messagingSenderId: '779857018826',
    projectId: 'shoppylist-519ba',
    storageBucket: 'shoppylist-519ba.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtbBG3yWpUp5VjPsb8VPBXCwfedHVZflw',
    appId: '1:779857018826:ios:bb4080c61d7cdf0d0f5933',
    messagingSenderId: '779857018826',
    projectId: 'shoppylist-519ba',
    storageBucket: 'shoppylist-519ba.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
